services:
  - type: web
    name: repl-nix-workspace
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000  # Change if you're binding to a specific port
    autoDeploy: true
