services:
  - type: web
    name: python-flask-app
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
    healthCheckPath: /
    numInstances: 1
    ports:
      - port: 5000
        protocol: http
    plan: free
    branch: main
    autoDeploy: true
